// --- BASE DE DATOS DE EJERCICIOS ---
export const EXERCISES = [
    // --- CUÁDRICEPS ---
    {n:"Sentadilla con Barra", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Frontal Barra", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Jaca (Hack)", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Jaca Inversa", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Cinturón", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Multipower", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Goblet", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Sissy", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Sissy Banco", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Sumo Mancuerna", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Búlgara Mancuernas", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Búlgara Multipower", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Pistol", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Zumo", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Jefferson", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Hack Sentado", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Sentadilla Pendulum", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Prensa de Piernas 45º", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Prensa Horizontal", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Prensa Vertical", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Prensa Unilateral", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Extensión Cuádriceps", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Extensión Cuádriceps Unilateral", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Zancadas Barra", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Zancadas Mancuernas", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Zancadas Caminando", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Zancadas Atrás Multipower", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Zancadas Estáticas", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Step-Up Cajón", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Step-Up con Barra", img:"cuadriceps.png", m:"Cuádriceps"},
    {n:"Aductores en Máquina", img:"cuadriceps.png", m:"Cuádriceps"},
    // --- ISQUIOTIBIALES (FEMORAL) ---
    {n:"Curl Femoral Tumbado", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Curl Femoral Sentado", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Curl Femoral de Pie", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Curl Femoral Unilateral", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Curl Nórdico", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Curl Nórdico Polea", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Curl Swiss Ball", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Peso Muerto Rumano Barra", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Peso Muerto Rumano Mancuernas", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Peso Muerto Rumano Multipower", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Peso Muerto Rumano Unilateral", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Peso Muerto Piernas Rígidas", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Buenos Días Barra", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Buenos Días Multipower", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Buenos Días Banda Elástica", img:"isquiotibiales.png", m:"Isquios"},
    {n:"Glute Ham Raise (GHR)", img:"isquiotibiales.png", m:"Isquios"},
    // --- GLÚTEOS ---
    {n:"Hip Thrust Barra", img:"gluteos.png", m:"Glúteos"},
    {n:"Hip Thrust Máquina", img:"gluteos.png", m:"Glúteos"},
    {n:"Hip Thrust Multipower", img:"gluteos.png", m:"Glúteos"},
    {n:"Hip Thrust Unilateral", img:"gluteos.png", m:"Glúteos"},
    {n:"Hip Thrust Mancuerna", img:"gluteos.png", m:"Glúteos"},
    {n:"Puente de Glúteo Suelo", img:"gluteos.png", m:"Glúteos"},
    {n:"Kas Glute Bridge", img:"gluteos.png", m:"Glúteos"},
    {n:"Sentadilla Búlgara (Enfoque Glúteo)", img:"gluteos.png", m:"Glúteos"},
    {n:"Patada Glúteo Polea", img:"gluteos.png", m:"Glúteos"},
    {n:"Patada Glúteo Máquina", img:"gluteos.png", m:"Glúteos"},
    {n:"Patada Glúteo Suelo", img:"gluteos.png", m:"Glúteos"},
    {n:"Abducción Máquina", img:"gluteos.png", m:"Glúteos"},
    {n:"Abducción Polea", img:"gluteos.png", m:"Glúteos"},
    {n:"Abducción con Gomas", img:"gluteos.png", m:"Glúteos"},
    {n:"Prensa Glúteos (Pies altos)", img:"gluteos.png", m:"Glúteos"},
    {n:"Frog Pumps", img:"gluteos.png", m:"Glúteos"},
    {n:"Step-Up Lateral", img:"gluteos.png", m:"Glúteos"},
    {n:"Pull Through Polea", img:"gluteos.png", m:"Glúteos"},
    {n:"Hiperextensiones Glúteo (45º)", img:"gluteos.png", m:"Glúteos"},
    {n:"Peso Muerto Sumo", img:"gluteos.png", m:"Glúteos"},
    {n:"Monster Walk", img:"gluteos.png", m:"Glúteos"},
    // --- GEMELOS ---
    {n:"Gemelo Sentado Máquina", img:"gemelos.png", m:"Gemelos"},
    {n:"Gemelo Sentado Barra", img:"gemelos.png", m:"Gemelos"},
    {n:"Gemelo de Pie Máquina", img:"gemelos.png", m:"Gemelos"},
    {n:"Gemelo de Pie Multipower", img:"gemelos.png", m:"Gemelos"},
    {n:"Gemelo de Pie Mancuernas", img:"gemelos.png", m:"Gemelos"},
    {n:"Gemelo en Prensa", img:"gemelos.png", m:"Gemelos"},
    {n:"Gemelo Donkey (Burro)", img:"gemelos.png", m:"Gemelos"},
    {n:"Gemelo Unilateral", img:"gemelos.png", m:"Gemelos"},
    {n:"Sóleo en Máquina", img:"gemelos.png", m:"Gemelos"},
    // --- ESPALDA ---
    {n:"Peso Muerto Convencional", img:"espalda.png", m:"Espalda"},
    {n:"Peso Muerto Déficit", img:"espalda.png", m:"Espalda"},
    {n:"Rack Pull", img:"espalda.png", m:"Espalda"},
    {n:"Dominadas Pronas", img:"espalda.png", m:"Espalda"},
    {n:"Dominadas Supinas", img:"espalda.png", m:"Espalda"},
    {n:"Dominadas Neutras", img:"espalda.png", m:"Espalda"},
    {n:"Dominadas Asistidas", img:"espalda.png", m:"Espalda"},
    {n:"Jalón al Pecho", img:"espalda.png", m:"Espalda"},
    {n:"Jalón al Pecho Supino", img:"espalda.png", m:"Espalda"},
    {n:"Jalón Cerrado (Triángulo)", img:"espalda.png", m:"Espalda"},
    {n:"Jalón Neutro", img:"espalda.png", m:"Espalda"},
    {n:"Jalón Unilateral Polea", img:"espalda.png", m:"Espalda"},
    {n:"Jalón Trasnuca", img:"espalda.png", m:"Espalda"},
    {n:"Jalón Brazos Rectos (Pullover Polea)", img:"espalda.png", m:"Espalda"},
    {n:"Remo con Barra 90º", img:"espalda.png", m:"Espalda"},
    {n:"Remo con Barra 45º (Yates)", img:"espalda.png", m:"Espalda"},
    {n:"Remo Pendlay", img:"espalda.png", m:"Espalda"},
    {n:"Remo Mancuerna Unilateral", img:"espalda.png", m:"Espalda"},
    {n:"Remo Mancuerna Dos Brazos", img:"espalda.png", m:"Espalda"},
    {n:"Remo Mancuernas Apoyo Pecho", img:"espalda.png", m:"Espalda"},
    {n:"Remo T (Barra esquina)", img:"espalda.png", m:"Espalda"},
    {n:"Remo T con Apoyo Pecho", img:"espalda.png", m:"Espalda"},
    {n:"Remo Gironda (Polea Baja)", img:"espalda.png", m:"Espalda"},
    {n:"Remo en Punta", img:"espalda.png", m:"Espalda"},
    {n:"Remo Kroc", img:"espalda.png", m:"Espalda"},
    {n:"Remo Meadows", img:"espalda.png", m:"Espalda"},
    {n:"Remo Máquina Placas", img:"espalda.png", m:"Espalda"},
    {n:"Remo Máquina Discos (Hammer)", img:"espalda.png", m:"Espalda"},
    {n:"Remo Invertido (TRX/Barra)", img:"espalda.png", m:"Espalda"},
    {n:"Remo al Mentón (Cuello)", img:"espalda.png", m:"Espalda"},
    {n:"Hiperextensiones Lumbares", img:"espalda.png", m:"Espalda"},
    {n:"Superman Suelo", img:"espalda.png", m:"Espalda"},
    {n:"Face Pull", img:"hombros.png", m:"Hombros"},
    // --- PECHO ---
    {n:"Press Banca Barra", img:"pecho.png", m:"Pecho"},
    {n:"Press Banca Mancuernas", img:"pecho.png", m:"Pecho"},
    {n:"Press Banca Multipower", img:"pecho.png", m:"Pecho"},
    {n:"Press Inclinado Barra", img:"pecho.png", m:"Pecho"},
    {n:"Press Inclinado Mancuernas", img:"pecho.png", m:"Pecho"},
    {n:"Press Inclinado Multipower", img:"pecho.png", m:"Pecho"},
    {n:"Press Declinado Barra", img:"pecho.png", m:"Pecho"},
    {n:"Press Declinado Mancuernas", img:"pecho.png", m:"Pecho"},
    {n:"Press Declinado Multipower", img:"pecho.png", m:"Pecho"},
    {n:"Press Pecho Máquina Sentado", img:"pecho.png", m:"Pecho"},
    {n:"Press Hammer Strength", img:"pecho.png", m:"Pecho"},
    {n:"Press Iso-Lateral", img:"pecho.png", m:"Pecho"},
    {n:"Press Guillotina", img:"pecho.png", m:"Pecho"},
    {n:"Press Svend", img:"pecho.png", m:"Pecho"},
    {n:"Press Landmine", img:"pecho.png", m:"Pecho"},
    {n:"Press Suelo (Floor Press)", img:"pecho.png", m:"Pecho"},
    {n:"Aperturas Mancuernas Planas", img:"pecho.png", m:"Pecho"},
    {n:"Aperturas Mancuernas Inclinadas", img:"pecho.png", m:"Pecho"},
    {n:"Aperturas en Máquina (Peck Deck)", img:"pecho.png", m:"Pecho"},
    {n:"Contractora de Pecho", img:"pecho.png", m:"Pecho"},
    {n:"Cruce de Poleas Alta", img:"pecho.png", m:"Pecho"},
    {n:"Cruce de Poleas Media", img:"pecho.png", m:"Pecho"},
    {n:"Cruce de Poleas Baja", img:"pecho.png", m:"Pecho"},
    {n:"Fondos en Paralelas", img:"pecho.png", m:"Pecho"},
    {n:"Fondos Asistidos", img:"pecho.png", m:"Pecho"},
    {n:"Pullover Mancuerna", img:"pecho.png", m:"Pecho"},
    {n:"Flexiones (Push Ups)", img:"pecho.png", m:"Pecho"},
    {n:"Flexiones Inclinadas", img:"pecho.png", m:"Pecho"},
    {n:"Flexiones Declinadas", img:"pecho.png", m:"Pecho"},
    {n:"Flexiones Diamante", img:"pecho.png", m:"Pecho"},
    // --- HOMBROS ---
    {n:"Press Militar Barra de Pie", img:"hombros.png", m:"Hombros"},
    {n:"Press Militar Barra Sentado", img:"hombros.png", m:"Hombros"},
    {n:"Press Hombro Mancuernas", img:"hombros.png", m:"Hombros"},
    {n:"Press Hombro Multipower", img:"hombros.png", m:"Hombros"},
    {n:"Press Hombro Máquina", img:"hombros.png", m:"Hombros"},
    {n:"Press Arnold", img:"hombros.png", m:"Hombros"},
    {n:"Press Trasnuca", img:"hombros.png", m:"Hombros"},
    {n:"Press Landmine Unilateral", img:"hombros.png", m:"Hombros"},
    {n:"Elevaciones Laterales Mancuerna", img:"hombros.png", m:"Hombros"},
    {n:"Elevaciones Laterales Polea", img:"hombros.png", m:"Hombros"},
    {n:"Elevaciones Laterales Máquina", img:"hombros.png", m:"Hombros"},
    {n:"Elevaciones Laterales Sentado", img:"hombros.png", m:"Hombros"},
    {n:"Elevaciones Laterales Egipcias", img:"hombros.png", m:"Hombros"},
    {n:"Elevaciones Frontales Mancuerna", img:"hombros.png", m:"Hombros"},
    {n:"Elevaciones Frontales Barra", img:"hombros.png", m:"Hombros"},
    {n:"Elevaciones Frontales Disco", img:"hombros.png", m:"Hombros"},
    {n:"Elevaciones Frontales Polea", img:"hombros.png", m:"Hombros"},
    {n:"Pájaros Mancuerna (Posterior)", img:"hombros.png", m:"Hombros"},
    {n:"Pájaros en Máquina", img:"hombros.png", m:"Hombros"},
    {n:"Face Pull Polea Alta", img:"hombros.png", m:"Hombros"},
    {n:"Cruces Polea Inversos", img:"hombros.png", m:"Hombros"},
    {n:"Remo al Mentón Barra", img:"hombros.png", m:"Hombros"},
    {n:"Remo al Mentón Polea", img:"hombros.png", m:"Hombros"},
    {n:"Encogimientos Barra (Trapecio)", img:"hombros.png", m:"Hombros"},
    {n:"Encogimientos Mancuerna", img:"hombros.png", m:"Hombros"},
    {n:"Encogimientos Multipower", img:"hombros.png", m:"Hombros"},
    {n:"Encogimientos en Máquina", img:"hombros.png", m:"Hombros"},
    {n:"Y-Raise Mancuernas", img:"hombros.png", m:"Hombros"},
    // --- BÍCEPS ---
    {n:"Curl con Barra Recta", img:"biceps.png", m:"Bíceps"},
    {n:"Curl con Barra Z", img:"biceps.png", m:"Bíceps"},
    {n:"Curl con Mancuernas Supino", img:"biceps.png", m:"Bíceps"},
    {n:"Curl con Mancuernas Alterno", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Martillo Mancuernas", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Martillo Cuerda Polea", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Predicador Barra Z (Scott)", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Predicador Mancuerna", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Predicador Máquina", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Concentrado", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Araña (Spider Curl)", img:"biceps.png", m:"Bíceps"},
    {n:"Curl en Banco Inclinado", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Polea Baja", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Polea Alta (Doble)", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Bayesiano (Espalda a Polea)", img:"biceps.png", m:"Bíceps"},
    {n:"Curl 21", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Zottman", img:"biceps.png", m:"Bíceps"},
    {n:"Curl con Disco", img:"biceps.png", m:"Bíceps"},
    {n:"Dominadas Supinas (Bíceps)", img:"biceps.png", m:"Bíceps"},
    {n:"Curl de Muñeca (Antebrazo)", img:"biceps.png", m:"Bíceps"},
    {n:"Curl Inverso Barra (Antebrazo)", img:"biceps.png", m:"Bíceps"},
    // --- TRÍCEPS ---
    {n:"Extensión Polea Cuerda", img:"triceps.png", m:"Tríceps"},
    {n:"Extensión Polea Barra Recta", img:"triceps.png", m:"Tríceps"},
    {n:"Extensión Polea Barra V", img:"triceps.png", m:"Tríceps"},
    {n:"Extensión Polea Unilateral", img:"triceps.png", m:"Tríceps"},
    {n:"Extensión Katana", img:"triceps.png", m:"Tríceps"},
    {n:"Press Francés Barra Z", img:"triceps.png", m:"Tríceps"},
    {n:"Press Francés Mancuernas", img:"triceps.png", m:"Tríceps"},
    {n:"Press Francés Polea", img:"triceps.png", m:"Tríceps"},
    {n:"Rompecráneos", img:"triceps.png", m:"Tríceps"},
    {n:"Press Cerrado Barra", img:"triceps.png", m:"Tríceps"},
    {n:"Press Cerrado Multipower", img:"triceps.png", m:"Tríceps"},
    {n:"Fondos Tríceps (Dips)", img:"triceps.png", m:"Tríceps"},
    {n:"Fondos entre Bancos", img:"triceps.png", m:"Tríceps"},
    {n:"Fondos en Máquina", img:"triceps.png", m:"Tríceps"},
    {n:"Patada de Tríceps Mancuerna", img:"triceps.png", m:"Tríceps"},
    {n:"Patada de Tríceps Polea", img:"triceps.png", m:"Tríceps"},
    {n:"Copa Tríceps a Dos Manos", img:"triceps.png", m:"Tríceps"},
    {n:"Copa Tríceps Unilateral", img:"triceps.png", m:"Tríceps"},
    {n:"Extensiones Trasnuca Polea", img:"triceps.png", m:"Tríceps"},
    {n:"JM Press", img:"triceps.png", m:"Tríceps"},
    {n:"Tate Press", img:"triceps.png", m:"Tríceps"},
    // --- ABDOMINALES (ABS) ---
    {n:"Crunch Suelo", img:"abs.png", m:"Abs"},
    {n:"Crunch Polea Alta", img:"abs.png", m:"Abs"},
    {n:"Crunch Máquina", img:"abs.png", m:"Abs"},
    {n:"Crunch en Fitball", img:"abs.png", m:"Abs"},
    {n:"Elevación de Piernas Colgado", img:"abs.png", m:"Abs"},
    {n:"Elevación de Piernas Suelo", img:"abs.png", m:"Abs"},
    {n:"Elevación de Rodillas (Silla romana)", img:"abs.png", m:"Abs"},
    {n:"Rueda Abdominal (Ab Wheel)", img:"abs.png", m:"Abs"},
    {n:"Plancha Abdominal (Plank)", img:"abs.png", m:"Abs"},
    {n:"Plancha Lateral", img:"abs.png", m:"Abs"},
    {n:"V-Ups", img:"abs.png", m:"Abs"},
    {n:"Tijeras", img:"abs.png", m:"Abs"},
    {n:"Bicicleta", img:"abs.png", m:"Abs"},
    {n:"Mountain Climbers", img:"abs.png", m:"Abs"},
    {n:"Russian Twist (Giros)", img:"abs.png", m:"Abs"},
    {n:"Woodchopper Polea (Leñador)", img:"abs.png", m:"Abs"},
    {n:"Press Pallof", img:"abs.png", m:"Abs"},
    {n:"Toques de Talón", img:"abs.png", m:"Abs"},
    {n:"Hipopresivos", img:"abs.png", m:"Abs"},
    {n:"Dragon Flag", img:"abs.png", m:"Abs"},
    // --- ANTIGUOS ---
    {n:"Sentadilla con Barra", img:"cuadriceps.png", m:"Cuádriceps"}, {n:"Sentadilla Jaca", img:"cuadriceps.png", m:"Cuádriceps"}, {n:"Sentadilla Cinturón", img:"cuadriceps.png", m:"Cuádriceps"}, {n:"Prensa de Piernas", img:"cuadriceps.png", m:"Cuádriceps"}, {n:"Extensión Cuádriceps", img:"cuadriceps.png", m:"Cuádriceps"}, {n:"Zancadas Mancuernas", img:"cuadriceps.png", m:"Cuádriceps"}, {n:"Curl Femoral Tumbado", img:"isquiotibiales.png", m:"Isquios"}, {n:"Curl Femoral Sentado", img:"isquiotibiales.png", m:"Isquios"}, {n:"Prensa Horizontal", img:"cuadriceps.png", m:"Cuádriceps"}, {n:"Prensa 45 Grados", img:"cuadriceps.png", m:"Cuádriceps"}, {n:"Gemelo Sentado", img:"gemelos.png", m:"Gemelos"}, {n:"Gemelo de Pie", img:"gemelos.png", m:"Gemelos"}, {n:"Gemelo Máquina", img:"gemelos.png", m:"Gemelos"}, {n:"Hip Thrust", img:"gluteos.png", m:"Glúteos"}, {n:"Sentadilla Búlgara", img:"gluteos.png", m:"Glúteos"}, {n:"Patada Glúteo Polea", img:"gluteos.png", m:"Glúteos"}, {n:"Abducción Máquina", img:"gluteos.png", m:"Glúteos"}, {n:"Prensa Glúteos", img:"gluteos.png", m:"Glúteos"}, {n:"Peso Muerto Rumano", img:"isquiotibiales.png", m:"Isquios"}, {n:"Peso Muerto", img:"espalda.png", m:"Espalda"}, {n:"Peso Muerto Sumo", img:"espalda.png", m:"Espalda"}, {n:"Remo con Barra", img:"espalda.png", m:"Espalda"}, {n:"Remo Mancuernas", img:"espalda.png", m:"Espalda"}, {n:"Jalón al Pecho", img:"espalda.png", m:"Espalda"}, {n:"Jalón Cerrado", img:"espalda.png", m:"Espalda"}, {n:"Remo en Máquina", img:"espalda.png", m:"Espalda"}, {n:"Remo Polea Baja", img:"espalda.png", m:"Espalda"}, {n:"Dominadas", img:"espalda.png", m:"Espalda"}, {n:"Dominadas Asistidas", img:"espalda.png", m:"Espalda"}, {n:"Remo Invertido", img:"espalda.png", m:"Espalda"}, {n:"Remo T", img:"espalda.png", m:"Espalda"}, {n:"Hiperextensiones", img:"espalda.png", m:"Espalda"}, {n:"Buenos Días", img:"isquiotibiales.png", m:"Isquios"}, {n:"Remo Hammer", img:"espalda.png", m:"Espalda"}, {n:"Jalón Neutro", img:"espalda.png", m:"Espalda"}, {n:"Jalón Abierto", img:"espalda.png", m:"Espalda"}, {n:"Remo al Cuello", img:"espalda.png", m:"Espalda"}, {n:"Press Banca", img:"pecho.png", m:"Pecho"}, {n:"Press Inclinado Mancuernas", img:"pecho.png", m:"Pecho"}, {n:"Aperturas Mancuernas", img:"pecho.png", m:"Pecho"}, {n:"Cruce de Poleas", img:"pecho.png", m:"Pecho"}, {n:"Press Máquina", img:"pecho.png", m:"Pecho"}, {n:"Press Declinado", img:"pecho.png", m:"Pecho"}, {n:"Fondos", img:"triceps.png", m:"Tríceps"}, {n:"Contractora Pecho", img:"pecho.png", m:"Pecho"}, {n:"Press Inclinado Barra", img:"pecho.png", m:"Pecho"}, {n:"Press Plano Mancuernas", img:"pecho.png", m:"Pecho"}, {n:"Press Iso Lateral", img:"pecho.png", m:"Pecho"}, {n:"Press Vertical", img:"pecho.png", m:"Pecho"}, {n:"Encogimientos Barra", img:"hombros.png", m:"Hombros"}, {n:"Encogimientos Mancuerna", img:"hombros.png", m:"Hombros"}, {n:"Press Militar", img:"hombros.png", m:"Hombros"}, {n:"Press Hombro Mancuerna", img:"hombros.png", m:"Hombros"}, {n:"Press Hombro Máquina", img:"hombros.png", m:"Hombros"}, {n:"Elevaciones Laterales", img:"hombros.png", m:"Hombros"}, {n:"Elevaciones Frontales", img:"hombros.png", m:"Hombros"}, {n:"Pájaros", img:"hombros.png", m:"Hombros"}, {n:"Laterales Polea", img:"hombros.png", m:"Hombros"}, {n:"Press Arnold", img:"hombros.png", m:"Hombros"}, {n:"Press Trasnuca", img:"hombros.png", m:"Hombros"}, {n:"Face Pull", img:"hombros.png", m:"Hombros"}, {n:"Curl Barra", img:"biceps.png", m:"Bíceps"}, {n:"Curl Mancuernas", img:"biceps.png", m:"Bíceps"}, {n:"Curl Polea", img:"biceps.png", m:"Bíceps"}, {n:"Curl Martillo", img:"biceps.png", m:"Bíceps"}, {n:"Curl Concentrado", img:"biceps.png", m:"Bíceps"}, {n:"Curl Predicador", img:"biceps.png", m:"Bíceps"}, {n:"Extensión Polea", img:"triceps.png", m:"Tríceps"}, {n:"Press Francés", img:"triceps.png", m:"Tríceps"}, {n:"Rompecráneos", img:"triceps.png", m:"Tríceps"}, {n:"Fondos Tríceps", img:"triceps.png", m:"Tríceps"}, {n:"Extensión Unilateral", img:"triceps.png", m:"Tríceps"}, {n:"Patada Tríceps", img:"triceps.png", m:"Tríceps"}, {n:"Copa Tríceps", img:"triceps.png", m:"Tríceps"}, {n:"Elevaciones Posteriores", img:"hombros.png", m:"Hombros"}, {n:"Rueda Abdominal", img:"abs.png", m:"Abs"}, {n:"Crunch Polea", img:"abs.png", m:"Abs"}, {n:"Elevación Piernas", img:"abs.png", m:"Abs"}, {n:"Abdominales Banco", img:"abs.png", m:"Abs"}, {n:"Crunch Máquina", img:"abs.png", m:"Abs"}, {n:"Rodillas al Pecho", img:"abs.png", m:"Abs"}, {n:"Abductor", img:"cuadriceps.png", m:"Cuádriceps"}, {n:"Extensión Triceps Barra", img:"triceps.png", m:"Tríceps"},
];